# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='seen'),
        ),
    ]
