# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_dialog_dialog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='dialog_status',
            field=models.BooleanField(default=True, verbose_name='dialog_status'),
        ),
    ]
