# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20180501_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='dialog_status',
        ),
        migrations.AddField(
            model_name='dialog',
            name='dialog_status_opponent',
            field=models.BooleanField(default=True, verbose_name='dialog_status_opponent'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='dialog_status_owner',
            field=models.BooleanField(default=True, verbose_name='dialog_status_owner'),
        ),
    ]
