# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20180504_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_del_msg',
            field=models.BooleanField(default=False, verbose_name='Receiver_delete_msg'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_del_msg',
            field=models.BooleanField(default=False, verbose_name='Auther_delete_msg'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='messages_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Seen'),
        ),
    ]
