from django.conf.urls import url
from .views import (
	CityListAPIView,
	CityDeleteAPIView,
	CityUpdateAPIView,
	CityCreateAPIView,
	CategoryCreateAPIView,
	CategoryListAPIView,
	CategoryUpdateAPIView,
	CategoryDeleteAPIView,
	SubCategoryCreateAPIView,
	SubCategoryListAPIView,
	SubCategoryUpdateAPIView,
	SubCategoryDeleteAPIView,
	ShopListAPIView,
	ShopDetailAPIView,
	FeedbackListAPIView,
	FeedbackCreateAPIView,
	FeedbackUpdateAPIView,
	VoteShop,
	RateShop,
	FreeListingAPIView,
	PricingListAPIView,
	)

urlpatterns = [
	url(r'^cities/$',CityListAPIView.as_view(),name="listCity"),
#    url(r'^addcity/$',CityCreateAPIView.as_view(),name="addCity"),
#    url(r'^(?P<id>\d+)/editcity/$',CityUpdateAPIView.as_view(),name="updateCity"),
#    url(r'^(?P<id>\d+)/deletecity/$',CityDeleteAPIView.as_view(),name="deleteCity"),
	url(r'^categories/$',CategoryListAPIView.as_view(),name="listCategories"),
#    url(r'^addcategory/$',CategoryCreateAPIView.as_view(),name="addCategory"),
#    url(r'^(?P<id>\d+)/editcategory/$',CategoryUpdateAPIView.as_view(),name="updateCategory"),
#    url(r'^(?P<id>\d+)/deletecategory/$',CategoryDeleteAPIView.as_view(),name="deleteCategory"),
	url(r'^subcategories/$',SubCategoryListAPIView.as_view(),name="listSubCategories"),
#    url(r'^addsubcategory/$',SubCategoryCreateAPIView.as_view(),name="addSubCategory"),
#    url(r'^(?P<id>\d+)/editsubcategory/$',SubCategoryUpdateAPIView.as_view(),name="updateSubcategory"),
#    url(r'^(?P<id>\d+)/deletesubcategory/$',SubCategoryDeleteAPIView.as_view(),name="deleteSubcategory"),
	url(r'^(?P<cityId>\d+)/(?P<subCatId>\d+)/shops/$',ShopListAPIView.as_view(),name="listshop"),
	url(r'^shops/(?P<slug>[\w-]+)/$',ShopDetailAPIView.as_view(),name="detailshop"),
	url(r'^feedbacks/$',FeedbackListAPIView.as_view(),name="listFeedback"),
	url(r'^feedback/add/$',FeedbackCreateAPIView.as_view(),name="addFeedback"),
#	url(r'^feedback/(?P<id>\d+)/edit/$',FeedbackUpdateAPIView.as_view(),name="editFeedback"),
	url(r'^vote/$',VoteShop.as_view(),name="vote"),
	url(r'^rate/$',RateShop.as_view(),name="rate"),
	url(r'freelist/$',FreeListingAPIView.as_view(),name="freeList"),
	url(r'pricing/(?P<slug>[\w-]+)/$',PricingListAPIView.as_view(),name="PricingList")
]