# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='heightField',
        ),
        migrations.RemoveField(
            model_name='category',
            name='widthField',
        ),
    ]
