# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170707_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='filtertag',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AddField(
            model_name='shop',
            name='pricingTabName',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCatImg',
            field=models.FileField(default='subCatImg/None/default.png', upload_to='subCatImg/'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
    ]
