# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170709_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subCatImg',
            field=models.FileField(default='subCatImg/None/default.svg', upload_to='subCatImg/'),
        ),
    ]
