# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170709_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(choices=[('raebareli', 'Raebareli'), ('lucknow', 'Lucknow'), ('gorakhpur', 'Gorakhpur'), ('deoria', 'Deoria')], max_length=120),
        ),
    ]
