# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 09:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180813_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoprating',
            name='duration',
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='shoprating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
