# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180813_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cityapl_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
